webiny/docs.webiny.com

docs/project-structure.md
=> Simple spelling correction

docs/get-started/quick-start.md
I added a brief sentence at the beginning of the Quick Start page, which highlights the end goal of the steps that are described in it.
Once the user reads it, he will have a better understanding of what's in front of him.
=> Highlight Quick Start goals

docs/webiny-apps/form-builder/triggers.md
Remove duplicate usage of the word `user`
=> Fixed a typo in the "Webiny Form Builder - Triggers" article

docs/api-development/plugins-reference.md
In reference to the [issue](https://github.com/webiny/webiny-js/issues/819)
As `graphql-context` plugin has been renamed to `context` 
This PR updates plugin reference to reflect the same
Before:
After:
=> Update `graphql-context` plugin reference in docs

docs/webiny-apps/admin/development/header-elements.md, docs/webiny-apps/admin/development/menus.md, docs/webiny-apps/admin/development/plugins-reference/app.md
In regards to issue #69
update admin app plugin reference to use `admin` prefix in case of following plugins:
- header-left
- header-middle
- header-right
- menu
=> Update admin app plugin reference

docs/webiny-apps/page-builder/development/rendering-pages.md
closes #58 
The motivation for this was that a reference to `apps/site/src/plugins/index.js` is no longer there in the new sample-project directory, which was replaced with:
`apps/site/src/index.js`
which references this import statement:
`import createSite, { SiteAppOptions } from "@webiny/app-template-site"`
I fixed up some wording in the paragraph below that section, the plugins after this section seemed to line up with the code within `@webiny/app-template-site/src/index.js` well enough.
=> Rename plugins/index.js to proper template.

docs/guides/headless-nextjs-tutorial.md
Hi 👋
In the Next.js guide we no longer need to polyfill the `fetch` api as it is automatically supported out of the box as of [Next.js 9.4](https://nextjs.org/blog/next-9-4#improved-built-in-fetch-support).
=> Remove polyfilling node-fetch in next.js example

docs/guides/headless-gatsby-tutorial.md
Hi all!
I have been checking out the project (and loving it so far!), going through the guide on getting set up with `Gatsby`, and I noticed a couple references to `Next.js` that I changed. I left the ones to images because I believe those images only exist in the Next.js guides.
=> Fix references to Next.js in Gatsby tutorial

docs/app-development/create-app-template/basic-template.md
Fix broken links
---
`app-template` links were pointing to `develop` branch which no longer exists. I've updated these links to point to the `master` branch.
=> update `app-template` links

docs/get-started/quick-start.md
> It seems, here `you` is misspelled with `your`.
=> fix(docs): Use "you" instead of "your" in quick-start section

docs/api-development/commodo/introduction.md, docs/api-development/introduction.md, docs/app-development/introduction.md, docs/deep-dive/plugins-crash-course.md, docs/get-started/quick-start.md, docs/guides/aws-credentials.md, docs/guides/get-started/aws-credentials.md, docs/guides/get-started/mongodb-atlas.md, docs/guides/mongodb-atlas.md
This PR changes the width of the iframes embedded within the docs to `100%` so they will render properly on smaller screens as well.
As I was going through the documentation I noticed that the fixed width of `805px` was causing the videos to not render correctly, causing the page layout to break.
This will allow the videos to render the full width of the page still, it's not the best solution since the height is a fixed value but to offer a fully responsive video it should probably open a PR to `docusaurus` repo.
=> fix: Make sure videos render properly on smaller screens

docs/how-to-guides/deployment/deploy-your-project.mdx, docs/how-to-guides/deployment/destroy-cloud-infrastructure.mdx
In few places, we still had `site` instead of `website` in `yarn webiny app ...` command.
=> fix: replace site with website in webiny app command

docs/tutorials/create-an-application/admin-area-package.mdx, docs/tutorials/create-an-application/api-package.mdx
Fix for a broken introduction link
- [Api package Introduction url change](https://deploy-preview-254--webiny-docs.netlify.app/docs/tutorials/create-an-application/api-package)
- [Admin module Introduction url change](https://deploy-preview-254--webiny-docs.netlify.app/docs/tutorials/create-an-application/admin-area-package)
=> fix(create-an-application): links towards the introduction

docs/tutorials/page-builder/create-a-new-page-builder-element.mdx
Fix one bug in the code example of [create a new page builder element](https://www.webiny.com/docs/tutorials/page-builder/create-a-new-page-builder-element#overview) tutorial.
=> fix: target property in PbEditorPageElementPlugin example 

docs/tutorials/page-builder/create-a-new-page-builder-element.mdx
This PR adds the missing information about the `install` and `build` of a new package in webiny project.
- [Updated the prerequisites section of create a new page builder element page](https://deploy-preview-273--webiny-docs.netlify.app/docs/tutorials/page-builder/create-a-new-page-builder-element#prerequisites)
=> feat: add install and build steps in create a new Page Builder element tutorial

docs/tutorials/headless-cms/create-a-webiny-headless-cms-address-field-plugin.mdx
https://github.com/webiny/webiny-js/issues/1616
A fix of the wrong webiny commands in the Tutorials / Headless CMS / Create a Webiny Headless CMS address field plugin.
Also added imports to the examples.
- [Create a Webiny Headless CMS address field plugin](https://deploy-preview-282--webiny-docs.netlify.app/docs/tutorials/headless-cms/create-a-webiny-headless-cms-address-field-plugin)
=> fix(headless-cms): wrong webiny commands

docs/changelog/5.10.0.mdx, docs/changelog/5.9.0.mdx, docs/how-to-guides/upgrade-webiny/5.9.0-to-5.10.0.mdx, website/sidebars.js
Creates the Webiny 5.10.0 changelog and upgrade guide.
[Upgrade guide](https://deploy-preview-305--webiny-docs.netlify.app/docs/how-to-guides/upgrade-webiny/5.9.0-to-5.10.0)
[Changelog](https://deploy-preview-305--webiny-docs.netlify.app/docs/changelog/5.10.0)
=> Webiny 5.10.0

docs/how-to-guides/webiny-applications/page-builder/extend-page-settings.mdx
This PR adds a section about DateTime field to the Extend Page Settings guide.
- https://deploy-preview-324--webiny-docs.netlify.app/docs/how-to-guides/webiny-applications/page-builder/extend-page-settings#handling-datetime-fields
=> feat: add a section on DateTime fields

docs/how-to-guides/webiny-cli/scaffolding/ci-cd.mdx
The current CI/CD scaffold for GH relies on GH Environments. Environments are not supported by private repos, unless these are under a GH Ent account. This PR adds messaging to the scaffold docs with the types of repos supported by the scaffold.
https://deploy-preview-328--webiny-docs.netlify.app/docs/how-to-guides/webiny-cli/scaffolding/ci-cd/
=> docs: updated reqs for the installation of this scaffold - private repos only supported under GH Ent accounts

docs/release-notes/5.17.0/upgrade-guide.mdx
Add patch note for the 5.17.0 upgrade guide
- [Added patch notes](https://deploy-preview-352--webiny-docs.netlify.app/docs/release-notes/5.17.0/upgrade-guide/#4-patch-the-migration)
=> fix(upgrade-guide): patch for the 5.17.0

docs/how-to-guides/deployment/aws/credentials.mdx
Fixes the tip box at the start, see screenshot below.
- [Configure AWS Credentials](https://www.webiny.com/docs/how-to-guides/deployment/aws/configure-aws-credentials/)
- [Preview](https://deploy-preview-358--webiny-docs.netlify.app/docs/how-to-guides/deployment/aws/configure-aws-credentials)
=> Fix tip box

docs/webiny-overview/serverless-cms/apps/intro.mdx, website/sidebars.js
Thanks: Adrian & Pedro for the inputs.
Renamed Webiny Applications menu to Serverless CMS. 
Also added the extend GraphQL API guide to the menu again.
I removed it while [menu restructuring](https://github.com/webiny/docs.webiny.com/pull/347); I was not sure that this would be relevant after our new scaffold. I discussed this with @doitadrian, and we concluded it is still relevant and gives way to users who manually want to extend GraphQL API with lesser code.  
https://deploy-preview-362--webiny-docs.netlify.app/docs
N/A
N/A
=> docs: renamed Webiny Applications menu to Serverless CMS & added the extend GraphQL API guide to menu

docs/key-topics/headless-cms/lifecycle-events.mdx
Add a check before attaching cms event
=> fix(key-topics): headless cms lifecycle events

docs/how-to-guides/webiny-applications/headless-cms/content-model-plugins.mdx
Renamed `ContentModelGroupPlugin` to `CmsGroupPlugin` and `ContentModelPlugin` to `CmsModelPlugin`.
- [Content Model Plugins](https://deploy-preview-377--webiny-docs.netlify.app/docs/how-to-guides/webiny-applications/headless-cms/content-model-plugins/)
=> refactor(content-model-plugins): rename plugins

docs/how-to-guides/integrations/integrate-tailwindcss.mdx
Some old commands were not working; replaced them with the new ones.
Reference: for fixing  package installation, took the reference from https://github.com/tailwindlabs/tailwindcss/issues/3432#issuecomment-770011986
Preview: [Tailwind CSS integration](https://deploy-preview-368--webiny-docs.netlify.app/docs/how-to-guides/integrations/integrate-tailwindcss)
Rest are N/A
N/A
=> docs: updated some commands and improved a statement in Tailwind guide

docusaurus.config.js
The 'Edit this page' option is footer was broken because it was forming the incorrect URL i.e. having `/docs/` twice in URL, fixed it by updating the `editUrl` property in  docusaurus config.
https://deploy-preview-388--webiny-docs.netlify.app/docs/webiny/introduction/
Rest are not applicable.
=> fix: 'Edit this page' option in footer was broken, corrected the editUrl to fix it

docs/enterprise/okta-integration.mdx
Page: https://www.webiny.com/docs/enterprise/okta-integration
- Updated 'JWT token claims' to 'JSON Web Token (JWT) claims', for first occurrence. Since the 'T' in JWT stands for 'token', if we write 'JWT token', 'token' is repeated twice. 
Source: https://jwt.io/introduction
- I updated the Note as follows, for better readability. If you agree, please accept it.
Current: there are two files, one for the `graphql` and one for the `headlessCMS` Lambda function, you need to update. Please grab the corresponding code from their dedicated tabs below. The code is similar, but _not_ the same.
Updated: You need to update two files, one each for the `graphql` and `headlessCMS` Lambda functions. Please grab the corresponding code from their dedicated tabs below. The code is similar, but _not_ the …
=> Request for minor updates

docs/release-notes/5.19.0/changelog.mdx
Page: https://www.webiny.com/docs/release-notes/5.19.0/changelog
- The link text in 'Searching the Reference Field for Any Version of the Entry (#2067)' shows '2067', but the link leads to 2068 content, which seems correct. So, I updated the link text from 2067 to 2068. If you agree, I request you to accept this update.
N/A
=> Request to update link text

docs/tutorials/create-custom-application/graphql-api.mdx
Page: https://www.webiny.com/docs/tutorials/create-custom-application/graphql-api
- In the 'Retrieving the GraphQL API URL' section, the 'webiny output' link leads to the correct page but displays the wrong (yarn webiny disable-telemetry) command. I updated to the correct link that leads to the 'webiny output' command. I request you to accept the update, if you agree.
N/A
=> Request to update 'webiny output' command link

src/pages/docs/page-builder/extending/customize-an-existing-element.mdx
Updated some obsolete code patterns of customizing existing page element.
N/A
=> docs: updated code references customize existing page element as per the new pattern

src/pages/docs/headless-cms/integrations/nextjs.mdx
Docs page has incorrect import instructions for the beta release of v5.25.0, this update that and another syntactical error.
=> fix(nextjs): update rich text module import instructions

src/navs/documentation.js
Put back links to headless CMS integrations in nav menu (pages were still there)
=> fix(navs): put back headless cms integrations links

src/pages/docs/overview/introduction.mdx
It seems during refactoring an extra `*` were left in Webiny word. Removed it and made it a normal word. 
-
N/A
=> docs: fixed the typo in making a text bold

src/pages/docs/release-notes/5.25.0/upgrade-guide.mdx
Added missing 5.25.0 upgrade project notes.
- [Upgrade command](https://docs-webiny-com-git-feat-upgrade-5250-webiny.vercel.app/docs/release-notes/5.25.0/upgrade-guide#2-run-the-upgrade-command)
=> feat: upgrade notes for 5.25.0

src/pages/docs/infrastructure/basics/destroy-cloud-infrastructure.mdx
Fixed the broken link for `prod/index.ts` file
N/A
=> docs: fixed the broken link for prod/index.ts file

src/pages/docs/page-builder/extending/create-a-page-element.mdx
The create page element tutorial was broken after our recent type changes and after including the IFrame component in out of the box library. Fixed the types and other issues. 
- https://docs-webiny-com-git-fix-create-page-element-webiny.vercel.app/docs/page-builder/extending/create-a-page-element
N/A
=> docs: fixed the create page element tutorial as per the new types changes

src/docs/5.29.x/infrastructure/basics/destroy-cloud-infrastructure.mdx
This PR fixes the destroy command page - corrects the order of `destroy` command execution.
N/A
=> Destroy Command Docs - Fix Order of Execution

src/docs/5.29.x/enterprise/okta-integration.mdx
Build failing when Okta plugin is configured.
Added ts-ignore hint to the okta-sign-in widget import, since Okta doesn't support types and we recently introduced strict-mode.
https://docs-webiny-com-git-fix-okta-webiny.vercel.app/docs/enterprise/okta-integration
N/A
=> fix: Added ts-ignore hint to the okta-sign-in widget import

src/docs/5.33.x/headless-cms/extending/content-models-via-code.mdx
Warning about changing model via code definitions.
- [Immutable Code Definitions in Model](https://docs-webiny-ck0iavwaw-webiny.vercel.app/docs/headless-cms/extending/content-models-via-code#immutable-code-definitions)
N/A
=> fix(headless-cms): content models via code immutable definitions

src/docs/5.31.x/core-development-concepts/extending-and-customizing/add-custom-route-to-existing-lambda.mdx, src/docs/5.31.x/navigation.js
This PR adds an article on how to add new custom route to our existing Lambda handlers and to the API Gateway - so it is actually passed to the Lambda handler.
- [Adding Custom Route to Existing Lambda](https://docs-webiny-com-git-feat-custom-routes-webiny.vercel.app/docs/core-development-concepts/extending-and-customizing/add-custom-route-to-existing-lambda)
=> feat: adding custom routes

src/docs/5.29.x/core-development-concepts/basics/project-deployment.mdx, src/docs/5.33.x/headless-cms/extending/content-models-via-code.mdx
Please refer to the following new sections that have been added:
- [Failed to Read Pulumi Credentials File. ](https://docs-webiny-com-git-slack-thread-1-webiny.vercel.app/docs/core-development-concepts/basics/project-deployment#failed-to-read-pulumi-credentials-file-please-re-run-pulumi-login) 
- [How to Set a Default Value of a Field?](https://docs-webiny-com-git-slack-thread-1-webiny.vercel.app/docs/headless-cms/extending/content-models-via-code#how-to-set-a-default-value-of-a-field)
=> docs: migrated information from community Slack to Docs

src/docs/5.31.x/core-development-concepts/extending-and-customizing/add-custom-route-to-existing-lambda.mdx
Update the `Adding Custom Route to Existing Webiny Lambda` article to contain the dynamic route examples.
- [Dynamic API Gateway Route
](https://docs-webiny-9fg82nqss-webiny.vercel.app/docs/core-development-concepts/extending-and-customizing/add-custom-route-to-existing-lambda#dynamic-api-gateway-route)
- [Dynamic Webiny Handler Route](https://docs-webiny-9fg82nqss-webiny.vercel.app/docs/core-development-concepts/extending-and-customizing/add-custom-route-to-existing-lambda#dynamic-webiny-handler-route)
=> feat: add dynamic custom route to the article

src/docs/5.28.x/overview/applications/headless-cms.mdx
Fixed Typo: next -> nest
- Typo on [https://www.webiny.com/docs/overview/applications/headless-cms](https://www.webiny.com/docs/overview/applications/headless-cms)
=> Fix Typo "nest"

src/docs/shared/release-notes/5.34.0/page-builder-pe-rendering-engine-migration.mdx
After working through the migration guide I found a few things I'd propose fixing. 
* Typos
* updated code block of `theme.ts` file
http://localhost:3000/docs/release-notes/5.34.0/page-builder-pe-rendering-engine-migration
=> Fixed a few typos and updated theme.ts code block

package.json, scripts/versionedDocs/prepareDocs.js, yarn.lock
Update to the `unstable` version of `@webiny/react-properties`, which contains a fix for unique property id generation. The IDs were not unique enough for the amount of properties being generated, and that caused the generated page data to be corrupted, thus making the build fail.
=> fix: update to latest react-properties

src/docs/5.37.x/headless-cms/integrations/legacy-render-rich-text-content.mdx
With this PR we want to add a new topic to the legacy rich text renderer article where we describe the sanitization option and call developers to upgrade the version of this component to `5.37.2` to improve the security of their website.
[Legacy RTE renderer page](https://docs-webiny-n62raqsxv-webiny.vercel.app/docs/headless-cms/integrations/legacy-render-rich-text-content)
N/A
=> Add html sanatization topic or legacy RTE renderer article

src/docs/5.29.x/infrastructure/additional-resources/connect-custom-domain.mdx
If the user just copy/paste the previous snippet their project will be deployed as a completely new one since they haven't included the pulumiResourceNamePrefix attribute which is by default present in their project. Thanks to Sven for reporting and sharing the updated code sample.
=> docs: fix the sample code to configure the custom domain in website app, thanks to Sven.

src/docs/shared/release-notes/5.35.0/removing-the-headless-cms-lambda-function.mdx
Fix a typo on the page
https://www.webiny.com/docs/release-notes/5.35.0/removing-the-headless-cms-lambda-function
=> docs: fixed typo in release notes

docs/developer-docs/5.39.x/file-manager/extending/customize-file-list-table-columns.mdx, docs/developer-docs/5.39.x/headless-cms/extending/customize-entry-list-table-columns.mdx
With this PR, we aim to fix the namespace for column configurations from the `Browser.Column` to `Browser.Table.Column`.
- [File Manager](https://www.webiny.com/docs/file-manager/extending/customize-file-list-table-columns)
- [Headless CMS](https://www.webiny.com/docs/headless-cms/extending/customize-entry-list-table-columns)
N/A
=> fix: column namespace

docs/developer-docs/5.40.x/headless-cms/extending/private-models.mdx
During the installation wizard of Webiny loading the private model does cause an error. The reason is that loading models requires i18n, but when the installation wizard launches, the setup of i18n is not done yet.
This minor documentation patch will update the example code of the books app to show case how to check if the CMS is already installed.
Only if the CMS is installed, the apps ContextPlugin code will be run.
Helped-by: Pavel Denisjuk <pavel@webiny.com>
---
CC: @swapnilmmane
=> docs: update private model documentation
