webiny/docs.webiny.com

- docs/deep-dive/plugins-crash-course.md
- docs/get-started/quick-start.md
Part of this PR is by @danruss - cheers man 🍻🚀
> fix: add code highlight and database connection note.

- docs/api-development/commodo/crash-course.md
Fixed a typo in the "Commodo Crash Course" article,  in the "Custom validation" code example.
> Fixed a typo in the "Commodo Crash Course" article

- docs/get-started/quick-start.md
> Fix: AWS credentials setup instructions

- docs/webiny-apps/page-builder/development/themes/elements.md
Can you check this out @EmilK15? :)
> refactor: replaced webiny-cms to webiny-pb

- docs/get-started/development-principles.md
Fix broken url, and swap @webiny/api reference to @webiny/graphql reference. Also add note on created watch mechanism for deployed components.
> Updated development principles

- docs/get-started/quick-start.md
- docs/get-started/template-setup/cwp-template-cms.md
- docs/get-started/template-setup/cwp-template-full.md
Swap full and CMS title positions.
> Rename template Titles, add clarification for AWS.

- docs/get-started/quick-start.md
> Add note about how to setup AWS in Getting Started.

- docs/webiny-apps/admin/development/plugins-reference/app.md
> Next admin dev plugin ref

- docs/get-started/configuration.md
- docs/get-started/quick-start.md
- website/sidebars.js
Here's an article explaining `webiny.root.js` & `webiny.config.js`
resolves #86
> Configuration article (webiny.root.js & webiny.config.js)

- docs/get-started/going-live.md
add how to remove deployed stack
> feat: add deploy specific resource

- docs/guides/headless-gatsby-tutorial.md
Improvement: tell the devs how to fetch new CMS data
resolves #124
> Gatsby + Webiny Headless CMS tutorial improvements

- docs/guides/headless-gatsby-tutorial.md
- docs/guides/headless-nextjs-tutorial.md
> Refactor Gatsby + CMS guide

- docs/faq/how-long-does-it-take-to-deploy.md
- docs/get-started/quick-start.md
- website/sidebars.js
Wrote some lines regarding deployment time.
Closes #119
> Faq how long does it take to deploy

- docs/faq/can-i-host-webiny-on-my-laptop.md
- website/sidebars.js
> Add "Can I host Webiny on my laptop?" to FAQ

- docs/faq/is-webiny-free.md
- website/sidebars.js
> feat: add "Is Webiny Free?" FAQ article

- docs/api-development/commodo/introduction.md
- docs/get-started/quick-start.md
- docs/guides/aws-credentials.md
- docs/guides/mongodb-atlas.md
- website/docusaurus.config.js
- Update page title
- Update the YT embed videos
Closes #161
> Update docs title page

- docs/guides/headless-gatsby-tutorial.md
- docs/guides/headless-nextjs-tutorial.md
> fix: add note about `Rich Text` field

- docs/tutorials/build-a-portfolio-website-with-react-webiny-apollo.md
Change localhost link to web accessible link.
Just made a simple update to a link that wasn't working.
> Update link pointing at localhost

- docs/faq/can-i-host-webiny-on-my-laptop.md
- docs/faq/how-is-webiny-serverless.md
Fixing a few small errors in the docs.
> Small spelling and punctuation errors

- docs/get-started/quick-start.md
Minor fix to avoid install failure due to jest dependency.
I didn't change the second line... and can't see what has changed.
> Update min node version in quick-start.md - fixes #176

- docs/deep-dive/stacks.md
> Fix: add `deploy` stage to `api` and `cdn` resources

- docs/how-to-guides/headless-cms/create-a-webiny-headless-cms-field-plugin.mdx
- docs/tutorials/headless-cms/create-a-webiny-headless-cms-address-field-plugin.mdx
- docs/tutorials/headless-cms/create-a-webiny-headless-cms-avatar-field-plugin.mdx
- website/sidebars.js
I linked code examples in our Webiny examples repository. Link is currently not working since i linked to master branch and my code is still in the PR:
https://github.com/webiny/webiny-examples/tree/feature/v5/headless-cms/address-field/headless-cms/address-field-tutorial
Master branch url will be:
https://github.com/webiny/webiny-examples/tree/master/headless-cms/address-field-tutorial
> feature: tutorial on how to create a headless cms field

- docs/webiny-overview/security.mdx
- website/sidebars.js
This PR adds a `Security` article to give a high-level overview of different aspects of security: security of dependencies, app security, etc.
> Security overview

- docs/changelog/5.5.0.mdx
Describe a filtering by reference field id possibility.
There are two examples added. One for listing articles with author (or multiple) and one for listing articles that do not contain given author(s).
> feat(changelog): describe filtering by reference field id

- docs/tutorials/create-an-application/admin-area-package.mdx
- docs/tutorials/create-an-application/api-package.mdx
More detailed explanation on how to add a new field in Create an Application tutorial - API part.
> fix(create-an-application): explain more in detail how to add a new field

- docs/how-to-guides/headless-cms/rendering-rich-text.mdx
- website/sidebars.js
This PR adds a guide for rendering of rich text content.
https://deploy-preview-267--webiny-docs.netlify.app/docs/how-to-guides/headless-cms/rendering-rich-text/
> Rendering rich text

- docs/changelog/5.10.0.mdx
- docs/changelog/5.9.0.mdx
- docs/how-to-guides/upgrade-webiny/5.9.0-to-5.10.0.mdx
- website/sidebars.js
Add changelog and upgrade instructions for v5.10.0
> Webiny 5.10.0

- docs/changelog/5.11.1.mdx
- docs/how-to-guides/upgrade-webiny/5.11.0-to-5.11.1.mdx
- website/sidebars.js
Changelog and Upgrade guide for v5.11.1
- Changelog: https://deploy-preview-318--webiny-docs.netlify.app/docs/changelog/5.11.1
- Upgrade Guide: https://deploy-preview-318--webiny-docs.netlify.app/docs/how-to-guides/upgrade-webiny/5.11.0-to-5.11.1
N/A
> Webiny 5.11.1

- docs/key-topics/tools-libraries.mdx
- docs/key-topics/webiny-applications/headless-cms/graphql-api.mdx
- docs/webiny-overview/security.mdx
- docs/webiny-overview/serverless-cms/apps/file-manager.mdx
- docs/webiny-telemetry.mdx
This PR fixes some typos and suggests some grammar changes.
> docs: fix small spelling and grammar issues

- docs/how-to-guides/deployment/preview-deployments.mdx
- docs/how-to-guides/webiny-applications/file-manager/create-a-file-type-plugin.mdx
- docs/tutorials/create-a-package-in-monorepo.mdx
- docs/tutorials/extend-admin-area/extending-entities.mdx
- docs/tutorials/extend-admin-area/security/introduction.mdx
- docs/tutorials/page-builder/create-a-new-page-builder-element.mdx
- docs/tutorials/page-builder/customize-an-existing-page-builder-element.mdx
This PR is to track small updates to the documentation I propose while i am going though each tutorial
~Currently it is dependent on https://github.com/webiny/webiny-examples/pull/68 being merged~ - merged
> Tutorial edits

- website/docusaurus.config.js
This PR adds plausible.io analytics
> feat: add plausible.io to scripts in config

- docs/tutorials/page-builder/create-a-new-page-element.mdx
Done following improvements to the 'create a new Page Element' docs
- Added the specific executable steps to follow. In some places, the statements were like:
`... this file/code is showing this ...`
instead of these types of statements, added actual executable instructions and give the context to the reader like:
`.... create a file at this location... then make changes in this file...`
- Fixed the incomplete code
(devs like to copy and paste code from docs ;)
- Added various notes and tips to help the reader
- Removed the redundant code of the render element plugin
- Fixed broken links
- Removed the stale code and updated it with the new one
- Added the steps to download assets and place them in the appropriate place; the code doesn't work if the user missed these steps. 
- [Create a …
> docs: improved the 'create a new Page Element' docs

- docs/release-notes/5.19.1/changelog.mdx
- docs/release-notes/5.19.1/upgrade-guide.mdx
- website/sidebars.js
Notes for 5.19.1.
- [changelog](https://deploy-preview-364--webiny-docs.netlify.app/docs/release-notes/5.19.1/changelog/)
- [upgrade guide](https://deploy-preview-364--webiny-docs.netlify.app/docs/release-notes/5.19.1/upgrade-guide/)
> feat(release-notes): note about 5.19.1 release

- docs/how-to-guides/deployment/build-and-deploy-hooks.mdx
- website/sidebars.js
Added an article describing build and deploy hooks.
Deploy hooks were available for a long time now, build hooks will be introduced in 5.20.0 with https://github.com/webiny/webiny-js/pull/2079.
Page link:
`/docs/how-to-guides/deployment/build-and-deploy-hooks`
> Added an article about build & deploy hooks

- docs/how-to-guides/deployment/connect-custom-domain.mdx
Adding some missing commas, nothing major 😉
- Added two commas on the '[Connect Custom Domain](https://www.webiny.com/docs/how-to-guides/deployment/connect-custom-domain/)' page
N/A
> Adding missing commas

- docs/tutorials/create-custom-application/security/react-application/integrating-hosted-ui-authentication-flow.mdx
https://github.com/webiny/webiny-js/issues/2155#issuecomment-1001380018
Documentation have this code and this have a error.
`{identity.firstName.charAt(0)}`
this line should be
`{identity.displayName.charAt(0)}`
Looks like [example](https://github.com/webiny/webiny-examples/blob/master/create-custom-application/full-example/pinterest-clone/app/code/src/components/Layout.tsx#L49) fixed it
N/A
> docs: Update integrating-hosted-ui-authentication-flow.mdx

- docs/tutorials/create-custom-application/security/react-application/initial-setup.mdx
https://github.com/webiny/webiny-js/issues/2155#issuecomment-1001366894
N/A
> docs: Fix 'SecurityIdentity' only refers to a type, but is being used as a value here.

- docs/community-plugins/introduction.mdx
- website/sidebars.js
Explained the community plugins and how to create or contribute to community plugins.
- [Preview](https://deploy-preview-378--webiny-docs.netlify.app/docs/community-plugins/introduction/)
N/A
> docs: added the community plugins guide

- docs/release-notes/5.10.0/upgrade-guide.mdx
- docs/release-notes/5.11.0/upgrade-guide.mdx
- docs/release-notes/5.11.1/upgrade-guide.mdx
- docs/release-notes/5.12.0/upgrade-guide.mdx
- docs/release-notes/5.13.0/upgrade-guide.mdx
- docs/release-notes/5.14.0/upgrade-guide.mdx
- docs/release-notes/5.15.0/upgrade-guide.mdx
- docs/release-notes/5.16.0/upgrade-guide.mdx
- docs/release-notes/5.17.0/upgrade-guide.mdx
- docs/release-notes/5.18.0/upgrade-guide.mdx
- docs/release-notes/5.19.0/upgrade-guide.mdx
- docs/release-notes/5.19.1/upgrade-guide.mdx
- docs/release-notes/5.20.0/upgrade-guide.mdx
- docs/release-notes/5.21.0/upgrade-guide.mdx
- docs/release-notes/5.22.0/upgrade-guide.mdx
- docs/release-notes/5.22.1/changelog.mdx
- docs/release-notes/5.22.1/upgrade-guide.mdx
- docs/release-notes/5.8.0/upgrade-guide.mdx
- docs/release-notes/5.9.0/upgrade-guide.mdx
- docusaurus.config.js
- sidebars.js
This PR adds a changelog and upgrade instructions for v5.22.1.
> feat: add changelog for 5.22.1

- docs/webiny-overview/serverless-cms/apps/file-manager.mdx
Added the details on how users can get the image in different dimensions that are uploaded via File Manager. 
[Preview](https://deploy-preview-385--webiny-docs.netlify.app/docs/webiny-overview/serverless-cms/apps/file-manager#image-delivery-api)
Rest are not applicable. 
N/A
> docs: improved image delivery section - added the image resizing details

- docs/how-to-guides/scaffolding/extend-graphql-api.mdx
Page: https://www.webiny.com/docs/how-to-guides/scaffolding/extend-graphql-api
- Updated 'takefyo' to 'take' in this sentence:
There aren't any additional steps that you need to takefyo in order to enable multi-locale support.
- Updated 'behaviour' to 'behavior', as per Vale recommendation. 
N/A
> Request to update typo

- docs/how-to-guides/scaffolding/graphql-api.mdx
Page: https://www.webiny.com/docs/how-to-guides/scaffolding/graphql-api
- Updated 'the the' with 'the'.
- Updated 'behaviour' with 'behavior'.
N/A
> Request for minor updates

- docs/how-to-guides/webiny-applications/themes/page-builder/colors.mdx
Page:https://www.webiny.com/docs/how-to-guides/webiny-applications/themes/page-builder/colors/
- In the title, 'Saas Variables', I updated 'Saas' to 'Sass'. 
N/A
> Request to update Saas to Sass

- docs/key-topics/ci-cd/introduction.mdx
Page: https://www.webiny.com/docs/key-topics/ci-cd/introduction
- Updated 'Planing' to 'Planning'
- Updated 'severless' to 'serverless'
- Other updates are minor. Pls feel free to accept/reject these updates. 
N/A
> Request for updating typos, and other updates

- docs/key-topics/security-framework/react-security.mdx
Page: https://www.webiny.com/docs/key-topics/security-framework/react-security
- In this page, the 'app-plugin-security-cognito package' link does not work. Pavel provided the correct link, and I have added it now.
https://github.com/webiny/webiny-js/blob/c3b55cb9e7551410090a26cf09799b4c4b3627a3/packages/app-admin-cognito/src/index.tsx#L95-L102
- Updated 'JWT token' to 'JWT', since 'T' in JWT is 'token'. 
Source: https://jwt.io/introduction
- Updated 'his' to 'their', as per guidance for inclusion in the Vale output. 
- Updated Github to GitHub.
N/A
> Request to update broken link

- docs/key-topics/security-framework/api-security.mdx
Page: https://www.webiny.com/docs/key-topics/security-framework/api-security
- Updated 'his' to 'their', as per inclusive language suggestion by Vale, and general practice. 
N/A
> Request to update 'his' to 'their'

- docs/webiny-overview/serverless-cms/apps/form-builder.mdx
Page: https://www.webiny.com/docs/webiny-overview/serverless-cms/apps/form-builder
- No details are included since the title explains the update. If you agree, please accept the update. 
N/A
> Request - Update 'form builder' to 'Form Builder'

- docs/how-to-guides/use-watch-command.mdx
Page: https://www.webiny.com/docs/how-to-guides/use-watch-command/
- In the TIP, the package.json locations (https://github.com/webiny/webiny-js/blob/next/packages/cwp-template-aws/template/api/code/graphql/package.json#L2 and https://github.com/webiny/webiny-js/blob/next/packages/cwp-template-aws/template/api/code/headlessCMS/package.json#L2) display a 404 error for me. Please provide the correct links, and I will update the path accordingly.  
- I updated 'GitBash' to 'Git Bash'
Source: https://www.atlassian.com/git/tutorials/git-bash
N/A
> Request for updating .json path (If applicable) and GitBash to Git Bash

- docs/key-topics/ci-cd/testing-serverless-applications.mdx
Page: https://www.webiny.com/docs/key-topics/ci-cd/testing-serverless-applications/
- Updated SAM to AWS Serverless Application Model (SAM), if it is indeed the correct reference. 
Reference: https://aws.amazon.com/serverless/sam/
- Query - An email from Steve to Jeremy is included. It does not have context, or i might be missing it. We can add a leading sentence for the conversation, if feasible. For example, "The following solution/suggestion can be used to create temporary stacks when you create a serverless infrastructure:". 
On a personal front, thanks. I did not realise that 'serverless services often cannot be run on your local machine'.
N/A
> Request to update full form of SAM and a query

- docs/how-to-guides/deployment/deploy-your-project.mdx
Page: https://www.webiny.com/docs/how-to-guides/deployment/deploy-your-project
- In the Info section, 'Cloud Infrastructure State Files' links to the current page, 'Deploy Your Project'. I updated it to https://www.webiny.com/docs/key-topics/ci-cd/cloud-infrastructure-state-files/. If correct, please accept the update.
N/A
> Request for updating path

- docs/key-topics/deployment/environments.mdx
Page: https://www.webiny.com/docs/key-topics/deployment/environments/
- The 'Workflows' and 'Cloud Infrastructure' links seem to be incorrect. 
Under 'Info', 'Workflows' links to the same page. So, I updated the link to the Workflows topic, shown below.
https://www.webiny.com/docs/key-topics/ci-cd/workflows/
Under 'Watch out for extra costs', 'Cloud Infrastructure' links to the same page. So, I updated the link to the correct topic, shown below.
https://www.webiny.com/docs/key-topics/cloud-infrastructure/introduction
Pls accept the updates if you find them correct.
N/A
> Request to update links

- src/pages/docs/core-development-concepts/basics/project-deployment.mdx
- src/pages/docs/core-development-concepts/basics/watch-command.mdx
- src/pages/docs/core-development-concepts/ci-cd/introduction.mdx
- src/pages/docs/core-development-concepts/scaffolding/extend-graphql-api.mdx
- src/pages/docs/core-development-concepts/scaffolding/graphql-api.mdx
- src/pages/docs/core-development-concepts/security-framework/api-security.mdx
- src/pages/docs/core-development-concepts/security-framework/react-security.mdx
- src/pages/docs/custom-app-tutorial/adding-user-pools/adjusting-webiny-config-ts-configuration-file.mdx
- src/pages/docs/custom-app-tutorial/graphql-api/create-a-graphql-api.mdx
- src/pages/docs/custom-app-tutorial/securing-graphql-api/initial-setup.mdx
- src/pages/docs/enterprise/okta-integration.mdx
- src/pages/docs/overview/applications/form-builder.mdx
- src/pages/docs/overview/introduction.mdx
- src/pages/docs/page-builder/theming/colors.mdx
- src/pages/docs/release-notes/5.19.0/changelog.mdx
- src/pages/docs/release-notes/5.5.0/changelog.mdx
Credits: Thanks to @pradeephubgit for his contributions
Fixed various typos and broken link that were contributed by @pradeephubgit in the previous docs version. 
NA
N/A
> docs: fixed various typos and broken link

- README.md
Updated README file, added project set-up instructions and structure details.
https://github.com/webiny/docs.webiny.com/tree/docs/readme#readme
**N/A**
**N/A**
> docs: added the project set up instructions in README file

- README.md
Updated the Project structure title slightly, changed `s` to small-case
NA
NA
N/A
> docs: updated the Project structure title slightly

- src/pages/docs/core-development-concepts/extending-and-customizing/how-to-change-elasticsearch-index-name-to-contain-locale.mdx
Update Elasticsearch name change with examples of the operations needed to be done.
- [How To Change Elasticsearch Index Name To Contain Locale](https://docs-webiny-com-git-feat-elasticsearch-customizat-bacb8e-webiny.vercel.app/docs/core-development-concepts/extending-and-customizing/how-to-change-elasticsearch-index-name-to-contain-locale)
> feat: examples for elasticsearch operations

- src/navs/documentation.js
- src/pages/docs/write-with-webiny/write-with-webiny.mdx
- Adds a new page on how to write with Webiny
- Also adds a link to the navigation
> feat(pages): write with webiny

- src/navs/documentation.js
- src/navs/generateReleaseNotes.js
- src/pages/docs/release-notes/5.28.0/changelog.mdx
- src/pages/docs/release-notes/5.28.0/upgrade-guide.mdx
- src/utils/createPageList.js
- src/utils/navElements.js
Release notes for 5.28.0
- [Changelog](https://docs-webiny-com-git-feat-webiny-5280-webiny.vercel.app/docs/release-notes/5.28.0/changelog)
- [Upgrade Guide](https://docs-webiny-com-git-feat-webiny-5280-webiny.vercel.app/docs/release-notes/5.28.0/upgrade-guide)
> feat: webiny 5.28.0 and automated menu generation

- src/pages/docs/headless-cms/integrations/nextjs.mdx
- Update NextJS page with appropriate script to bootstrap a new project
> fix(headlesscms): update npx nextjs create script

- src/pages/docs/write-with-webiny/write-with-webiny.mdx
Thanks to Mislav for the copy.
We made the updates to Write with Webiny program, thus updated the 'How does it work?' section
https://docs-webiny-com-git-write-with-webiny-webiny.vercel.app/docs/write-with-webiny/write-with-webiny
N/A
> docs: improved the How Write With Webiny program work section

- src/pages/docs/release-notes/5.29.0/changelog.mdx
- src/pages/docs/release-notes/5.29.0/upgrade-guide.mdx
- yarn.lock
- [Changelog](https://docs-webiny-com-git-feat-webiny-5290-webiny.vercel.app/docs/release-notes/5.29.0/changelog)
- [Upgrade Guide](https://docs-webiny-com-git-feat-webiny-5290-webiny.vercel.app/docs/release-notes/5.29.0/upgrade-guide)
> Webiny 5.29.0

- src/pages/_document.js
Add Fathom tracking script which is already present on www.webiny.com
> feat(tracking): add fathom tracking script

- public/algolia/sitemap.xml
- src/docs/5.28.x/infrastructure/basics/build-and-deploy-hooks.mdx
- src/docs/5.29.x/infrastructure/basics/destroy-cloud-infrastructure.mdx
The "Destroy Cloud Infrastructure" page was still containing outdated ( < 5.29.0) information. 
N/A
> Update "Destroy Cloud Infrastructure"

- src/docs/5.29.x/core-development-concepts/project-organization/project-applications-and-packages.mdx
With this PR we fix the applications folder structure found on [this page](https://www.webiny.com/docs/core-development-concepts/project-organization/project-applications-and-packages), to reflect the new folder structure introduced after v5.29.0.
> fix: folder structure after v5.29

- src/docs/5.29.x/core-development-concepts/basics/project-deployment.mdx
- src/docs/5.29.x/headless-cms/extending/custom-field-type.mdx
Done following:
1. Fixed the following error for the `CmsModelFieldToGraphQLPlugin`
`Binding element 'field' implicitly has an 'any' type.`
2. Updated `pulumi` command as per the new directory structure of API
3.  added the `@types/cryptr` information for type definitions for `cryptr` package used in the create new field tutorial
N/A
> docs: fixed the TypeScript errors in custom field tutorial

- public/algolia/sitemap.xml
- src/docs/5.28.x/headless-cms/integrations/gatsby.mdx
- src/docs/5.28.x/headless-cms/integrations/nextjs.mdx
- Add missing API access token settings for the file manager
> fix(integrations): add missing API token permissions

- src/docs/shared/release-notes/5.33.1/changelog.mdx
- src/docs/shared/release-notes/5.33.1/upgrade-guide.mdx
A release which contains fix for converter used for alias to storageId
- [Changelog](https://docs-webiny-mpc3oei8e-webiny.vercel.app/docs/release-notes/5.33.1/changelog)
- [Upgrade Guide](https://docs-webiny-mpc3oei8e-webiny.vercel.app/docs/release-notes/5.33.1/upgrade-guide)
N/A
> feat: release notes and changelog for 5.33.1

- src/docs/shared/infrastructure/additional-resources/reset-state-without-redeploy.mdx
- Added a link to original docs on AWS
> fix(infrastructure): add link to originating AWS docs

- src/docs/5.28.x/navigation.js
- src/docs/5.28.x/overview/pricing.mdx
- src/docs/5.31.x/overview/features/security.mdx
> Added pricing tiers article

- public/algolia/sitemap.xml
- src/docs/shared/release-notes/5.33.2/changelog.mdx
- src/docs/shared/release-notes/5.33.2/upgrade-guide.mdx
Release notes for 5.33.2
- [Changelog](https://docs-webiny-com-git-feat-webiny-5332-webiny.vercel.app/docs/release-notes/5.33.2/changelog)
- [Upgrade Guide](https://docs-webiny-com-git-feat-webiny-5332-webiny.vercel.app/docs/release-notes/5.33.2/upgrade-guide)
N/A
> feat: release notes for 5.33.2

- public/algolia/sitemap.xml
- src/docs/5.33.x/headless-cms/extending/content-models-via-code.mdx
- Updated references to api folder to match new project structure
> fix(headlesscms): update folder paths

- public/algolia/sitemap.xml
- src/docs/5.29.x/core-development-concepts/basics/project-deployment.mdx
- src/docs/5.29.x/infrastructure/basics/modify-cloud-infrastructure.mdx
- src/docs/5.29.x/navigation.js
This PR introduces the Modify Cloud Infrastructure article. It explains how users can modify cloud infrastructure deployed by Webiny, using Pulumi.
https://docs-webiny-com-git-pulumi-adjustments-doc-webiny.vercel.app/docs/infrastructure/basics/modify-cloud-infrastructure
Updated the Project Deployment article. Some of the sentences were still referring to the old pre-5.29 project structure. Also, added a link to the new article, so that it's discovered more easily.
N/A
> Introduce "Modify Cloud Infrastructure" Article

- src/docs/5.33.x/navigation.js
- src/docs/5.33.x/performance-and-load-benchmark/headless-cms/performance-tuning.mdx
> Performance tuning for Headless CMS

- src/docs/shared/release-notes/5.33.5/changelog.mdx
- src/docs/shared/release-notes/5.33.5/upgrade-guide.mdx
Release notes and changelog for the 5.33.5 version of the system.
- [Changelog](https://docs-webiny-com-git-feat-webiny-5335-webiny.vercel.app/docs/release-notes/5.33.5/changelog)
- [Upgrade Guide](https://docs-webiny-com-git-feat-webiny-5335-webiny.vercel.app/docs/release-notes/5.33.5/upgrade-guide)
> feat: release notes and changelog for 5.33.5

- src/docs/5.34.x/headless-cms/basics/using-graphql-api-advanced-filtering.mdx
- src/docs/5.34.x/navigation.js
Document about the new advanced filtering in the Headless CMS GraphQL API.
- [Headless CMS Advanced GraphQL API filtering](https://docs-webiny-com-git-feat-headless-cmsgraphql-adva-8e987f-webiny.vercel.app/docs/headless-cms/basics/using-graphql-api-advanced-filtering)
N/A
> feat(headless-cms): advanced filtering

- src/components/page/Search.js
- src/css/main.css
- src/layouts/ContentsLayout.js
This PR improves the search results provided by Algolia, and reverts search dialog styling to the one provided by default by Algolia.
> fix: improve algolia search results

- src/docs/5.34.x/core-development-concepts/extending-and-customizing/intercepting-the-request.mdx
- src/docs/5.34.x/navigation.js
This PR adds the article on how to intercept the Fastify Request,how to modify it and even prevent further lifecycle events from being executed.
- [Intercepting the Request](https://docs-webiny-iikz6h9t0-webiny.vercel.app/docs/core-development-concepts/extending-and-customizing/intercepting-the-request)
N/A
> feat: intercepting the handler request

- src/docs/5.34.x/overview/features/mailer.mdx
Explanation of the environment variable required for the Mailer Settings via UI to work.
> fix: secret environment variable for mailer settings

- src/docs/5.34.x/headless-cms/extending/custom-sorting.mdx
- src/docs/5.34.x/navigation.js
- src/docs/shared/release-notes/5.34.1/changelog.mdx
Changelog 
Headless CMS custom sorting article
N/A
> feat: headless cms custom sorting + changelog

- src/docs/5.34.x/navigation.js
- src/docs/5.34.x/overview/features/sso-and-custom-authenticators.mdx
> Added article about SSO and custom auth

- scripts/versionedDocs/prepareDocs.js
- src/docs/5.34.x/enterprise/theme-manager.mdx
- src/docs/5.34.x/headless-cms/extending/custom-sorting.mdx
- src/docs/5.34.x/navigation.js
- src/docs/shared/release-notes/5.34.1/changelog.mdx
- src/docs/shared/release-notes/5.34.1/upgrade-guide.mdx
This PR creates the 5.34.1 release notes and additional related documentation.
> Webiny 5.34.1

- src/docs/shared/release-notes/5.34.3/changelog.mdx
- src/docs/shared/release-notes/5.34.3/upgrade-guide.mdx
This PR adds the 5.34.3 release notes.
> Webiny 5.34.3

- src/docs/shared/release-notes/5.34.4/changelog.mdx
- src/docs/shared/release-notes/5.34.4/upgrade-guide.mdx
This PR creates the 5.34.4 release notes.
> 5.34.4 Release Notes

- src/docs/shared/release-notes/5.34.5/changelog.mdx
- src/docs/shared/release-notes/5.34.5/upgrade-guide.mdx
This PR creates 5.34.5 release notes.
> Create 5.34.5 Release Notes

- src/docs/5.34.x/infrastructure/basics/best-practices.mdx
- src/docs/5.34.x/navigation.js
> Added infra best practices article

- src/docs/5.28.x/core-development-concepts/basics/webiny-cli.mdx
- src/docs/5.34.x/enterprise/use-existing-amazon-vpc.mdx
- src/docs/5.34.x/navigation.js
- src/docs/5.34.x/overview/features/security.mdx
- src/docs/shared/release-notes/5.34.6/changelog.mdx
- src/docs/shared/release-notes/5.34.6/upgrade-guide.mdx
This PR creates the 5.34.6 docs.
> Webiny 5.34.6

- src/docs/shared/release-notes/5.34.7/changelog.mdx
- src/docs/shared/release-notes/5.34.7/upgrade-guide.mdx
This PR creates the 5.34.7 release notes.
> 5.34.7 Release Notes

- src/components/page/Header.js
Also, added an icon for the Webiny website link
> docs: update the main menu, show respective user guides or developer docs link based on user's current page

- src/docs/5.35.x/core-development-concepts/basics/importing-plugins.mdx
- src/docs/5.35.x/core-development-concepts/extending-and-customizing/extend-graphql-api.mdx
- src/docs/5.35.x/enterprise/auth0-integration.mdx
- src/docs/5.35.x/enterprise/okta-integration.mdx
- src/docs/5.35.x/headless-cms/extending/content-models-via-code.mdx
- src/docs/5.35.x/headless-cms/extending/custom-field-type.mdx
- src/docs/5.35.x/headless-cms/references/storage-transform-plugin.mdx
Changes in the docs to reflect the removal of the Headless CMS Lambda.
> fix: update docs containing headless cms lambda references

- src/docs/shared/release-notes/5.35.3/changelog.mdx
- src/docs/shared/release-notes/5.35.3/upgrade-guide.mdx
- src/docs/shared/release-notes/5.35.4/changelog.mdx
- src/docs/shared/release-notes/5.35.4/upgrade-guide.mdx
Release notes and upgrade guide for 5.35.3 and 5.35.4 versions.
> feat: 5.35.3 + 5.35.4 release note

- src/docs/5.28.x/get-started/install-webiny.mdx
https://docs-webiny-adb7z2g8h-webiny.vercel.app/docs/get-started/install-webiny
N/A
> docs: added note that once user made database selection in setup, it cannot be changed later

- src/docs/5.39.x/core-development-concepts/basics/routes-and-events.mdx
- src/docs/5.39.x/core-development-concepts/extending-and-customizing/add-custom-route-to-existing-lambda.mdx
- src/docs/5.39.x/navigation.js
- [Routes and events](https://docs-webiny-59sie9gfl-webiny.vercel.app/docs/core-development-concepts/basics/routes-and-events)
- [Adding custom route to existing lambda](https://docs-webiny-59sie9gfl-webiny.vercel.app/docs/core-development-concepts/extending-and-customizing/add-custom-route-to-existing-lambda)
> feat: 5.39.0 routes and events

- docs/developer-docs/5.38.x/get-started/install-webiny.mdx
- docs/release-notes/5.38.3/changelog.mdx
- docs/release-notes/5.38.3/upgrade-guide.mdx
This PR creates 5.38.3 release notes.
> 5.38.3 Release Notes

- docs/developer-docs/5.33.x/admin-area/extending/custom-dashboard.mdx
- docs/developer-docs/5.33.x/navigation.tsx
This PR adds an article on dashboard customization.
- [Custom Dashboard](https://docs-webiny-com-git-feat-custom-dashboard-webiny.vercel.app/docs/admin-area/extending/custom-dashboard)
> feat: custom dashboard article

- docs/release-notes/5.39.1/changelog.mdx
- docs/release-notes/5.39.1/upgrade-guide.mdx
Changelog for 5.39.1.
- [Changelog](https://docs-webiny-com-git-release-5391-webiny.vercel.app/docs/release-notes/5.39.1/changelog)
> feat: 5.39.1 changelog

- docs/release-notes/5.39.3/changelog.mdx
- docs/release-notes/5.39.3/upgrade-guide.mdx
This PR creates the 5.39.3 release notes.
> 5.39.3 Release Notes

- docs/developer-docs/5.39.x/headless-cms/extending/content-models-via-code.mdx
- docs/developer-docs/5.39.x/headless-cms/extending/private-models.mdx
> docs: higlighted the properties which must never change when creating content model via code

- docs/developer-docs/5.34.x/overview/features/mailer.mdx
Provide more info about Mailer transports.
> fix: provide more info about mailer transports

- docs/release-notes/5.39.0/upgrade-guide.mdx
- docs/release-notes/5.39.6/changelog.mdx
- docs/release-notes/5.39.6/upgrade-guide.mdx
This PR creates the 5.39.6 release notes.
> 5.39.6 Release Notes

- docs/release-notes/5.39.8/changelog.mdx
- docs/release-notes/5.39.8/upgrade-guide.mdx
Changelog for 5.39.8
- [Changelog](https://docs-webiny-com-git-release-5398-webiny.vercel.app/docs/release-notes/5.39.8/changelog)
> chore: 5.39.8 release notes

- docs/developer-docs/5.40.x/headless-cms/extending/content-models-via-code.mdx
- docs/release-notes/upgrade-webiny.mdx
[Can I Modify the Singular API Name and Plural API Name of a Model?](https://docs-webiny-com-git-slack-to-docs-webiny.vercel.app/docs/headless-cms/extending/content-models-via-code#can-i-modify-the-singular-api-name-and-plural-api-name-of-a-model)
[Where Can I Find Details on the Webiny Beta Releases?](https://docs-webiny-com-git-slack-to-docs-webiny.vercel.app/docs/release-notes/upgrade-webiny#where-can-i-find-details-on-the-webiny-beta-releases)
> docs: added details to update Singular API Name and Plural API Name of a model & details on the Webiny beta releases

- docs/developer-docs/5.40.x/headless-cms/extending/content-entry-traverser.mdx
- docs/release-notes/5.40.0/upgrade-guide.mdx
- docs/release-notes/5.40.2/changelog.mdx
- docs/release-notes/5.40.2/upgrade-guide.mdx
This PR creates the 5.40.2 release notes.
> Create 5.40.2 Release Notes

- docs/release-notes/5.40.3/changelog.mdx
- docs/release-notes/5.40.3/upgrade-guide.mdx
- [Changelog](https://docs-webiny-com-git-release-5403-webiny.vercel.app/docs/release-notes/5.40.3/changelog)
N/A
> Release 5.40.3

- docs/developer-docs/5.28.x/headless-cms/basics/using-graphql-api.mdx
https://docs-webiny-com-git-introspection-mode-webiny.vercel.app/docs/headless-cms/basics/using-graphql-api#how-can-i-disable-introspection-queries-in-the-graph-ql
> docs: added the FAQ about how to disable introspection queries in the GraphQL

- docs/release-notes/5.40.4/changelog.mdx
- docs/release-notes/5.40.4/upgrade-guide.mdx
Changelog for 5.40.4
- [Changelog](https://docs-webiny-com-git-release-5404-webiny.vercel.app/docs/release-notes/5.40.4/changelog)
- [Upgarde Guide](https://docs-webiny-com-git-release-5404-webiny.vercel.app/docs/release-notes/5.40.4/upgrade-guide)
> Release 5.40.4

- docs/developer-docs/5.39.x/core-development-concepts/background-tasks/how-to-handle-a-background-task-run.mdx
- docs/developer-docs/5.41.x/security/security-framework/api-security.mdx
- docs/developer-docs/5.41.x/security/security-framework/react-security.mdx
- docs/developer-docs/5.42.x/core-development-concepts/basics/logger.mdx
- docs/developer-docs/5.42.x/core-development-concepts/basics/user-project-upgrade.mdx
- docs/developer-docs/5.42.x/navigation.tsx
- docs/release-notes/5.42.0/changelog.mdx
- docs/release-notes/5.42.0/upgrade-guide.mdx
- docs/user-guides/5.42.x/navigation.tsx
- package.json
- src/components/CopyButton.js
- src/hooks/useHomepage.js
- src/layouts/SidebarLayout.js
- yarn.lock
This PR creates the 5.42.0 release notes.
- [Changelog](https://docs-webiny-com-git-release-5420-webiny.vercel.app/docs/release-notes/5.42.0/changelog)
- [Upgrade](https://docs-webiny-com-git-release-5420-webiny.vercel.app/docs/release-notes/5.42.0/upgrade-guide)
- [Webiny Logger (internal)](https://docs-webiny-com-git-release-5420-webiny.vercel.app/docs/core-development-concepts/basics/logger)
- [User Project Upgrade](https://docs-webiny-com-git-release-5420-webiny.vercel.app/docs/core-development-concepts/basics/user-project-upgrade)
> Create 5.42.0 Release Notes

- docs/developer-docs/5.39.x/core-development-concepts/background-tasks/background-task-management.mdx
- docs/developer-docs/5.39.x/core-development-concepts/background-tasks/built-in-background-tasks.mdx
Add more info for Elasticsearch indexes tasks.
> feat: elasticsearch indexes
